### ISSUE TITLE
bug: mediaflow proxy streams with Torrentio give playback error

### ISSUE THREAD

**Issue by FastZet** [Viren070/AIOStreams#26]
With Mediaflow enabled, getting a "oops player error: stremio encountered an error playing the media" in android app. Web stremio fails to play with vlc on android and PC. without mediaflow enabled addon is working fine.

**Comment by Viren070** [comment]
Does the same mediaflow configuration work on other addons like Jackettio and MediaFusion? 

How have you hosted MediaFlow?

**Comment by FastZet** [comment]
My mediaflow instance is hosted on a ubuntu vps. It works fine with Media Fusion. Haven't tried it with any other addon. I proxy both live stream and debrid stream with Media Fusion and it works fine with simultaneous uses.

**Comment by Viren070** [comment]
Have you checked your mediaflow logs? anything of notice there? 

Is it for every stream or just streams from a certain addon?

**Comment by nreis96** [comment]
This also happens to me specifically with all torrentio links. Using a VPS but works fine with mediafusion. Also no issues with stremthru wrapping torrentio if that helps somewhat

**Comment by Viren070** [comment]
Yes, Torrentio blocks requests from a VPS.

So when your mediaflow on your VPS attempts to access the Torrentio stream url, it gets blocked. 

It works fine with mediafusion because mediafusion does not block requests from a VPS

**Comment by Viren070** [comment]
I have added a way to customise which streams are proxied already (in https://github.com/Viren070/AIOStreams/commit/dcb0353f926cd2e72e5cd0d3e823d8436a4064ef) so you don't have to choose one or the other (proxy all streams but no torrentio or proxy 0 streams). 

You can choose whether to proxy streams from specific addons only, and/or from specific services only. 

It'll be on ElfHosted once I make a new release, which should be before the end of this week. You can try it right now by self hosting.

**Comment by mhdzumair** [comment]
> Yes, Torrentio blocks requests from a VPS.
> 
> So when your mediaflow on your VPS attempts to access the Torrentio stream url, it gets blocked.
> 
> It works fine with mediafusion because mediafusion does not block requests from a VPS

In that case, you can utilize the request proxy option in the mediaflow to access torrentio via proxy service such as cloudflare warp. Set the env vars as follows in MediaFlow.

```
PROXY_URL=socks5://warp:1080
TRANSPORT_ROUTES='{
    "https://torrentio.strem.fun": {
        "proxy": true
    }
}'
```
This will fetch the request redirection URL through warp proxy and then directly access the video url from RD. If you're using AD, then you need to access the video URL through warp as well in that case you can enable the request proxy globally by setting following env vars, 

```
PROXY_URL=socks5://warp:1080
ALL_PROXY=true
```

You may try this warp docker guide, https://github.com/cmj2002/warp-docker. I haven't tried it by myself.

**Comment by FastZet** [comment]
>Have you checked your mediaflow logs? anything of notice there?

I see a `403 forbidden` error in mediaflow log whenever I try to play a link with Torrentio.

>Is it for every stream or just streams from a certain addon?

Now that you have mentioned it, it is only happening with Torrentio. Media Fusion and Easynews+ is working fine.

Will try wrap as suggested by mediaflow dev.

**Comment by nreis96** [comment]
> > Have you checked your mediaflow logs? anything of notice there?
> 
> I see a `403 forbidden` error in mediaflow log whenever I try to play a link with Torrentio.
> 
> > Is it for every stream or just streams from a certain addon?
> 
> Now that you have mentioned it, it is only happening with Torrentio. Media Fusion and Easynews+ is working fine.
> 
> Will try wrap as suggested by mediaflow dev.

Let me know if it worked for you. I haven't tested yet. @BRKsays

**Comment by FastZet** [comment]
Not working with cloudflare wrap either. I think I'll stick to Media Fusion and give the Torrentio dev a W.

**Comment by nreis96** [comment]
I can confirm solution provided by @mhdzumair works! Thank you very much

**Comment by FastZet** [comment]
> I can confirm solution provided by [@mhdzumair](https://github.com/mhdzumair) works! Thank you very much

Can you briefly summarise the steps you took? I had installed the docker container for cf wrap within the same network and set the env var as provided. Still the error persisted. If I missed anything please tell.

**Comment by nreis96** [comment]
Hi @BRKsays ,

What @mhdzumair says is *exactly* what you should be doing. If you are not using a .env file and instead putting the vars in your compose file you need to have something like: https://ibb.co/fqybrYS

Obviously tailoring the warp address to that for your own setup

**Comment by janowakps** [comment]
> 
> ```
> PROXY_URL=socks5://warp:1080
> TRANSPORT_ROUTES='{
>     "https://torrentio.strem.fun": {
>         "proxy": true
>     }
> }'
> ```
> 
> This will fetch the request redirection URL through warp proxy and then directly access the video url from RD. 

@mhdzumair It seems that this might not be accurate. With this setup, I see the IP address of Warp, not my server’s IP when checking at https://real-debrid.com/downloads

**Comment by mhdzumair** [comment]
I just mentioned the guide for connecting to torrentio via warp. If you're using both mediafusion and torrentio then better to set default proxy by 
```
ALL_PROXY=true
```

Yes you should only see warp ip address in rd instesd of your server ip. Thats expected.

**Comment by FastZet** [comment]
Deployed mediaflow on a oracle vps and seems to be working for now. Hopefully Torrentio dev doesn't block this either. So my issue is resolved for now.

@Viren070, if it is all the same to you please close the issue.

**Comment by Viren070** [comment]
I'll leave it open so others can see the solution if needed.

**Comment by kodi-lover** [comment]
> Hi [@BRKsays](https://github.com/BRKsays) ,
> 
> What [@mhdzumair](https://github.com/mhdzumair) says is _exactly_ what you should be doing. If you are not using a .env file and instead putting the vars in your compose file you need to have something like: https://ibb.co/fqybrYS
> 
> Obviously tailoring the warp address to that for your own setup

When you say tailoring the warp address to that for your own setup, what do you mean by that exactly? I tried to copy and paste: 

PROXY_URL=socks5://warp:1080
TRANSPORT_ROUTES='{
    "https://torrentio.strem.fun": {
        "proxy": true
    }
}'

This still didn't work for me and still not getting torrentio links. what did u do exactly to get this to work?
